# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_user_description'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='user_from',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='login_register.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='user_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='login_register.User'),
            preserve_default=False,
        ),
    ]
